# APPLICATION CONFIG
spring:
  profiles:
    active: "dev"
  application:
    name: "spring-gateway-service"
    admin:
      enabled: false
  cloud:
    gateway:
      routes:
        - id: "auth_service_route"
          uri: "http://localhost:7002"
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: "CircuitBreaker"
              args:
                name: "authCircuitBreaker"
                fallbackuri: forward:/api/v1/fallback/
        - id: "user_service_route"
          uri: "http://localhost:7003"
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: "CircuitBreaker"
              args:
                name: "userCircuitBreaker"
                fallbackuri: forward:/api/v1/fallback/
            - AuthorizationFilter
#logging:
#  level:
#    root: "INFO"
#  file:
#    name: "logs/${spring.application.name}-${today:dd-MM-yyyy}-logs.log"
#  pattern:
#  logback:
#    rollingpolicy:
#      file-name-pattern: "logs/%d{yyyy-MM, aux}/${spring.application.name}.%d{dd-MM-yyyy}.%i.log"
#      max-file-size: "10MB"
#      total-size-cap: "1GB"
#      max-history: 10
server:
  port: 7000
  error:
    include-message: "always"

resilience4j:
  retry:
    instances:
      myRetry:
        max-attempts: 3
        wait-duration: 5s

rabbitmq:
  queue:
    authorization:
      request: "authorization.request.queue"
      response: "authorization.response.queue"
  exchange:
    authorization: "authorization.exchange"
